### ISSUE TITLE
설치 후 실행 중 error

### ISSUE THREAD

**Issue by Jees7** [DongjunLee/kino-bot#24]
- main.py를 Anaconda 가상환경에서 실행 과정에서 발생된 error message 입니다
- error message 중 log 파일은 생성되지 않았습니다

```
(venv_kino) D:\MyProgramFiles\Anaconda3\workspace\kino-bot>python main.py
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    kino_bot = KinoBot()
  File "D:\MyProgramFiles\Anaconda3\workspace\kino-bot\kino\bot.py", line 21, in __init__
    self.logger = Logger().get_logger()
  File "D:\MyProgramFiles\Anaconda3\workspace\kino-bot\kino\utils\logger.py", line 35, in __init__
    Logger.instance = Logger.__Logger()
  File "D:\MyProgramFiles\Anaconda3\workspace\kino-bot\kino\utils\logger.py", line 22, in __init__
    dirname + "/Kino_" + now.strftime("%Y-%m-%d %H:%M:%S") + ".log")
  File "D:\MyProgramFiles\Anaconda3\envs\venv_kino\lib\logging\__init__.py", line 1025, in __init__
    StreamHandler.__init__(self, self._open())
  File "D:\MyProgramFiles\Anaconda3\envs\venv_kino\lib\logging\__init__.py", line 1054, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 22] Invalid argument: 'D:\\MyProgramFiles\\Anaconda3\\workspace\\kino-bot\\log\\Kino_2017-05-24 04:00:21.log'

(venv_kino) D:\MyProgramFiles\Anaconda3\workspace\kino-bot>
```

**Comment by DongjunLee** [comment]
이 문제도 윈도우라서 생기는 문제로 보입니다.
kino/utils/logger.py 에서 보시면 

```python
dirname = './log'
if not os.path.isdir(dirname):
    os.mkdir(dirname)
fileHandler = logging.FileHandler(
    dirname + "/Kino_" + now.strftime("%Y-%m-%d %H:%M:%S") + ".log")
```

여기서 '/' 는 linux 에서 사용되는 경로입니다.

https://stackoverflow.com/questions/43196750/python-oserror-errno-22-invalid-argument
For example, characters like \, :, >, ... are not allowed in Windows filenames.

윈도우에 맞는 경로로 수정을 해주시면 로그쪽에 문제가 생기진 않을 것 입니다.

**Comment by Jees7** [comment]
경로 수정하니 슬랙봇에 hello 메시지까지 뜨는 것은 성공했습니다.
다만, data\ 하위 파일 읽기 부분에서 문제가 발생 되네요.

```
D:\MyProgramFiles\Anaconda3\envs\venv_kino\python.exe D:/MyProgramFiles/Anaconda3/workspace/kino-bot/main.py
[INFO|bot.py:37] 2017-05-27 15:40:24,772 > start real time messaging session!
[Errno 2] No such file or directory: 'data\\record\\2017-05-27.json'
[Errno 2] No such file or directory: 'data\\state.json'
[ERROR|listener.py:121] 2017-05-27 15:40:27,216 > Presence Listener Error: 'sleep'
[ERROR|listener.py:122] 2017-05-27 15:40:27,216 > presence
Traceback (most recent call last):
  File "D:\MyProgramFiles\Anaconda3\workspace\kino-bot\kino\listener.py", line 119, in handle_presence_change
    self.router.route(presence=self.msg['presence'])
  File "D:\MyProgramFiles\Anaconda3\workspace\kino-bot\kino\route.py", line 65, in route
    self.presence_manager.check_wake_up(presence)
  File "D:\MyProgramFiles\Anaconda3\workspace\kino-bot\kino\dialog\presence.py", line 36, in check_wake_up
    presence_log = state.current[state.SLEEP]
KeyError: 'sleep'
[Errno 2] No such file or directory: 'data\\record\\2017-05-27.json'
[ERROR|listener.py:121] 2017-05-27 15:40:28,545 > Presence Listener Error: 'sleep'
[Errno 2] No such file or directory: 'data\\state.json'
[ERROR|listener.py:122] 2017-05-27 15:40:28,545 > presence
Traceback (most recent call last):
  File "D:\MyProgramFiles\Anaconda3\workspace\kino-bot\kino\listener.py", line 119, in handle_presence_change
    self.router.route(presence=self.msg['presence'])
  File "D:\MyProgramFiles\Anaconda3\workspace\kino-bot\kino\route.py", line 65, in route
    self.presence_manager.check_wake_up(presence)
  File "D:\MyProgramFiles\Anaconda3\workspace\kino-bot\kino\dialog\presence.py", line 36, in check_wake_up
    presence_log = state.current[state.SLEEP]
KeyError: 'sleep'
```

- 위 로그의 2개의 파일( 'data\\record\\2017-05-27.json' 과 'data\\state.json')은 생성되지 않은 것으로 봐서 이 부분이 의심이 되는데, 다른 생각이 있는지 궁금합니다.
- 혹시 저의 config.json 파일 설정이 잘못 된 것이 아닌지도 의심이 됩니다.

**Comment by DongjunLee** [comment]
config.json 파일 설정의 문제는 아닌 것 같습니다
말씀해주신 대로 '위 로그의 2개의 파일( 'data\record\2017-05-27.json' 과 'data\state.json')은 생성되지 않은 것으로 봐서 이 부분이 의심' 이 부분이 문제일 것 입니다.

logger.py 부분에서와 마찬가지로, utils/data_handler.py 에는 data를 읽고 쓰는 경로가 지정되어있습니다.
이 부분들에 대해서도 경로 수정을 윈도우용으로 맞춰서 해주셔야할 것으로 보입니다..!

윈도우에서 돌리는 것에 대한 불편함이 굉장히 많네요ㅠㅠ
제가 윈도우로 테스트를 할 수도 없는 상황이라.. 지원을 잘 해드릴 수 없는 점이 아쉽습니다..!
